<a href="https://colab.research.google.com/github/vash050/pytorch_start/blob/main/start.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import torch

In [1]:
my_list = [1, 2, 3, 4, 5]
my_list

[1, 2, 3, 4, 5]

In [2]:
import numpy as np

In [3]:
np1 = np.random.rand(3,4)
np1

array([[0.67845419, 0.87101013, 0.33511246, 0.09673765],
       [0.25290682, 0.42025801, 0.30079563, 0.3193352 ],
       [0.6456052 , 0.95111228, 0.58851785, 0.85174151]])

In [6]:
tensor_2d = torch.randn(3,4)
tensor_2d

tensor([[-0.1476,  1.9418,  0.0208,  1.6143],
        [-2.0912, -0.4098,  0.1441,  0.4266],
        [-1.6732,  1.4526, -2.0107, -0.8664]])

In [7]:
tensor_3d = torch.zeros(2,3,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [8]:
my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.6785, 0.8710, 0.3351, 0.0967],
        [0.2529, 0.4203, 0.3008, 0.3193],
        [0.6456, 0.9511, 0.5885, 0.8517]], dtype=torch.float64)