<a href="https://colab.research.google.com/github/vash050/pytorch_start/blob/main/step_5_r.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import torch

In [2]:
# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43],
                   [91, 88, 64],
                   [87, 134, 58],
                   [102, 43, 37],
                   [69, 96, 70]], dtype='float32')

In [3]:
# Targets (apples, oranges)
targets = np.array([[56, 70],
                    [81, 101],
                    [119, 133],
                    [22, 37],
                    [103, 119]], dtype='float32')

In [4]:
# Convert inputs and targets to tensors
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)
print(inputs)
print(targets)

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])
tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [5]:
# Weights and biases
w = torch.randn(2, 3, requires_grad=True)
b = torch.randn(2, requires_grad=True)
print(w)
print(b)

tensor([[ 1.9947, -0.6075, -1.2235],
        [ 1.4677,  0.3938,  0.4199]], requires_grad=True)
tensor([0.5452, 0.0555], requires_grad=True)


In [6]:
def model(x):
    return x @ w.t() + b

In [7]:
preds = model(inputs)
print(preds)

tensor([[ 52.8420, 151.6400],
        [ 50.2946, 195.1468],
        [ 21.7098, 204.8727],
        [132.6100, 182.2323],
        [ -5.7900, 168.5272]], grad_fn=<AddBackward0>)


In [8]:
# Compare with targets
print(targets)

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [9]:
# MSE loss
def mse(t1, t2):
    diff = t1 - t2
    return torch.sum(diff * diff) / diff.numel()

In [10]:
# Compute loss
loss = mse(preds, targets)
print(loss)

tensor(7872.7764, grad_fn=<DivBackward0>)


In [11]:
# Compute gradients
loss.backward()

In [12]:
# Gradients for weights
print(w)
print(w.grad)

tensor([[ 1.9947, -0.6075, -1.2235],
        [ 1.4677,  0.3938,  0.4199]], requires_grad=True)
tensor([[-1542.6525, -4327.6318, -2253.3003],
        [ 7802.2144,  6877.0684,  4509.0063]])


In [13]:
with torch.no_grad():
    w -= w.grad * 1e-5
    b -= b.grad * 1e-5

In [14]:
# Let's verify that the loss is actually lower
loss = mse(preds, targets)
print(loss)

tensor(7872.7764, grad_fn=<DivBackward0>)


In [15]:
w.grad.zero_()
b.grad.zero_()
print(w.grad)
print(b.grad)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([0., 0.])


In [16]:
# Generate predictions
preds = model(inputs)
print(preds)

tensor([[ 57.8368, 139.3970],
        [ 56.9491, 179.1083],
        [ 30.1581, 186.2534],
        [136.8784, 169.6476],
        [  1.0065, 153.3845]], grad_fn=<AddBackward0>)


In [17]:
# Calculate the loss
loss = mse(preds, targets)
print(loss)

tensor(6460.4883, grad_fn=<DivBackward0>)


In [18]:
# Compute gradients
loss.backward()
print(w.grad)
print(b.grad)

tensor([[-1020.7483, -3749.9656, -1900.4293],
        [ 6541.8950,  5532.7695,  3677.3159]])
tensor([-19.6342,  73.5582])


In [19]:
# Adjust weights & reset gradients
with torch.no_grad():
    w -= w.grad * 1e-5
    b -= b.grad * 1e-5
    w.grad.zero_()
    b.grad.zero_()

In [20]:
print(w)
print(b)

tensor([[ 2.0203, -0.5268, -1.1820],
        [ 1.3243,  0.2697,  0.3380]], requires_grad=True)
tensor([0.5457, 0.0539], requires_grad=True)


In [21]:
print(w)
print(b)

tensor([[ 2.0203, -0.5268, -1.1820],
        [ 1.3243,  0.2697,  0.3380]], requires_grad=True)
tensor([0.5457, 0.0539], requires_grad=True)


In [22]:
# Calculate loss
preds = model(inputs)
loss = mse(preds, targets)
print(loss)

tensor(5494.7490, grad_fn=<DivBackward0>)


In [23]:
# Train for 100 epochs
for i in range(100):
    preds = model(inputs)
    loss = mse(preds, targets)
    loss.backward()
    with torch.no_grad():
        w -= w.grad * 1e-5
        b -= b.grad * 1e-5
        w.grad.zero_()
        b.grad.zero_()

In [24]:
# Calculate loss
preds = model(inputs)
loss = mse(preds, targets)
print(loss)

tensor(1096.5969, grad_fn=<DivBackward0>)


In [25]:
# Predictions
preds

tensor([[ 70.5047,  77.5515],
        [ 80.6511, 101.6040],
        [100.7879, 119.1915],
        [ 97.0227,  78.6646],
        [ 55.0040,  96.4667]], grad_fn=<AddBackward0>)

In [26]:
# Targets
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])