<a href="https://colab.research.google.com/github/vash050/pytorch_start/blob/main/step_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [2]:
import numpy as np


In [5]:
tensor_a = torch.tensor([1,2,3,4])
tensor_b = torch.tensor([6,7,8,9])

In [6]:
tensor_a + tensor_b

tensor([ 7,  9, 11, 13])

In [7]:
tensor_b - tensor_a

tensor([5, 5, 5, 5])

In [8]:
torch.add(tensor_a, tensor_b)

tensor([ 7,  9, 11, 13])

In [9]:
torch.sub(tensor_b, tensor_a)

tensor([5, 5, 5, 5])

In [10]:
tensor_a * tensor_b

tensor([ 6, 14, 24, 36])

In [11]:
torch.mul(tensor_a, tensor_b)

tensor([ 6, 14, 24, 36])

In [12]:
tensor_b / tensor_a

tensor([6.0000, 3.5000, 2.6667, 2.2500])

In [13]:
torch.div(tensor_b, tensor_a)

tensor([6.0000, 3.5000, 2.6667, 2.2500])

In [14]:
tensor_b % tensor_a

tensor([0, 1, 2, 1])

In [15]:
torch.remainder(tensor_b, tensor_a)

tensor([0, 1, 2, 1])

In [16]:
torch.pow(tensor_a, tensor_b)

tensor([     1,    128,   6561, 262144])

In [17]:
tensor_a.add_(tensor_b)

tensor([ 7,  9, 11, 13])

In [18]:
tensor_a

tensor([ 7,  9, 11, 13])