<a href="https://colab.research.google.com/github/vash050/pytorch_start/blob/main/step_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
torch.__version__

'2.3.1+cu121'

In [4]:
t1 = torch.tensor(4.)
t1

tensor(4.)

In [5]:
t1.dtype

torch.float32

In [9]:
torch.full((1, 2, 10), 0)

tensor([[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]])

In [16]:
ten1 = torch.full((2,2,2), 0)
ten2 = torch.full((2,2,2), 1)
ten1


tensor([[[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 0]]])

In [17]:
ten2

tensor([[[1, 1],
         [1, 1]],

        [[1, 1],
         [1, 1]]])

In [19]:
ten3 = torch.cat((ten1, ten2))
ten3

tensor([[[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 0]],

        [[1, 1],
         [1, 1]],

        [[1, 1],
         [1, 1]]])

In [20]:
ten3.shape

torch.Size([4, 2, 2])

In [23]:
torch.is_tensor(ten3)

True

In [25]:
torch.numel(ten3)

16

In [26]:
import numpy as np
x = np.array([[1, 2], [3, 4.]])

In [27]:
y = torch.from_numpy(x)
y

tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)