<a href="https://colab.research.google.com/github/vash050/pytorch_start/blob/main/step_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [2]:
my_torch = torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
my_torch = my_torch.reshape(2,5)
my_torch

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [4]:
my_torch2 = torch.arange(10)
my_torch2

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
my_torch2 = my_torch2.reshape(5,-1)
my_torch2

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [8]:
my_torch2[2][1] = 145656
my_torch2

tensor([[     0,      1],
        [     2,      3],
        [     4, 145656],
        [     6,      7],
        [     8,      9]])

In [9]:
my_torch2[:,1]

tensor([     1,      3, 145656,      7,      9])

In [10]:
my_torch2[:,0]

tensor([0, 2, 4, 6, 8])

In [11]:
my_torch2[1:]

tensor([[     2,      3],
        [     4, 145656],
        [     6,      7],
        [     8,      9]])

In [13]:
my_torch2[1:0]

tensor([], size=(0, 2), dtype=torch.int64)

In [14]:
my_torch2[1:,0]

tensor([2, 4, 6, 8])

In [12]:
my_torch2[0:]

tensor([[     0,      1],
        [     2,      3],
        [     4, 145656],
        [     6,      7],
        [     8,      9]])

In [15]:
my_torch2[:,1:]

tensor([[     1],
        [     3],
        [145656],
        [     7],
        [     9]])