<a href="https://colab.research.google.com/github/vash050/pytorch_start/blob/main/step_6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch.nn as nn

In [2]:
import numpy as np


In [3]:
inputs = np.array([[73,67,43],
                   [91,88,64],
                   [87,134,58],
                   [102,43,37],
                   [69,96,70],
                   [74,66,43],
                   [91,87,65],
                   [88,134,59],
                   [101,44,37],
                   [68,96,71],
                   [73,66,44],
                   [92,87,64],
                   [87,135,57],
                   [103,43,36],
                   [68,97,70]],
                  dtype='float32')

In [6]:
targets = np.array([[56,70],
                   [81,101],
                   [119,133],
                   [22,37],
                   [103,119],
                   [57,69],
                   [80,102],
                   [118,134],
                   [21,38],
                   [104,118],
                   [57,69],
                   [82,100],
                   [118,134],
                   [20,38],
                   [102,120]],
                  dtype='float32'
                  )

In [5]:
inputs.shape

(15, 3)

In [7]:
targets.shape

(15, 2)

In [8]:
import torch

In [9]:
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)

In [10]:
inputs

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.],
        [ 74.,  66.,  43.],
        [ 91.,  87.,  65.],
        [ 88., 134.,  59.],
        [101.,  44.,  37.],
        [ 68.,  96.,  71.],
        [ 73.,  66.,  44.],
        [ 92.,  87.,  64.],
        [ 87., 135.,  57.],
        [103.,  43.,  36.],
        [ 68.,  97.,  70.]])

In [11]:
from torch.utils.data import TensorDataset

In [12]:
train_ds = TensorDataset(inputs, targets)
train_ds[0:3]

(tensor([[ 73.,  67.,  43.],
         [ 91.,  88.,  64.],
         [ 87., 134.,  58.]]),
 tensor([[ 56.,  70.],
         [ 81., 101.],
         [119., 133.]]))

In [13]:
from torch.utils.data import DataLoader

In [14]:
batch_size = 5
train_dl = DataLoader(train_ds, batch_size, shuffle=True)

In [17]:
for xb, yb in train_dl:
  print(xb)
  print(yb)
  break

tensor([[103.,  43.,  36.],
        [ 68.,  97.,  70.],
        [ 73.,  67.,  43.],
        [ 68.,  96.,  71.],
        [ 74.,  66.,  43.]])
tensor([[ 20.,  38.],
        [102., 120.],
        [ 56.,  70.],
        [104., 118.],
        [ 57.,  69.]])


In [21]:
model = nn.Linear(3,2)
print(model.weight)
print(model.bias)

Parameter containing:
tensor([[ 0.4668, -0.4472,  0.0783],
        [ 0.2683, -0.0843,  0.0163]], requires_grad=True)
Parameter containing:
tensor([0.3368, 0.2314], requires_grad=True)


In [22]:
list(model.parameters())

[Parameter containing:
 tensor([[ 0.4668, -0.4472,  0.0783],
         [ 0.2683, -0.0843,  0.0163]], requires_grad=True),
 Parameter containing:
 tensor([0.3368, 0.2314], requires_grad=True)]

In [25]:
preds = model(inputs)
preds

tensor([[  7.8189,  14.8647],
        [  8.4749,  18.2646],
        [-14.4328,  13.2141],
        [ 31.6188,  24.5709],
        [ -4.9024,  11.7857],
        [  8.7329,  15.2173],
        [  9.0004,  18.3652],
        [-13.8877,  13.4986],
        [ 30.7048,  24.2183],
        [ -5.2909,  11.5337],
        [  8.3444,  14.9654],
        [  9.3888,  18.6172],
        [-14.9583,  13.1135],
        [ 32.0073,  24.8229],
        [ -5.8164,  11.4331]], grad_fn=<AddmmBackward0>)

In [26]:
import torch.nn.functional as F

In [27]:
loss_fn = F.mse_loss

In [28]:
loss = loss_fn(model(inputs), targets)
print(loss)

tensor(7298.1323, grad_fn=<MseLossBackward0>)


In [29]:
opt = torch.optim.SGD(model.parameters(), lr=1e-5)

In [30]:
def fit(num_epochs, model, loss_fn, opt, train_dl):
  for epoch in range(num_epochs):
    for xb, yb, in train_dl:
      pred = model(xb)
      loss = loss_fn(pred, yb)
      loss.backward()
      opt.step()
      opt.zero_grad()
    if(epoch+1) % 10 == 0:
      print('Epoch [{}/{}], Loss:{:4f}'.format(epoch+1, num_epochs, loss.item()))

In [31]:
fit(100, model, loss_fn, opt, train_dl)

Epoch [10/100], Loss:1934.578857
Epoch [20/100], Loss:202.300858
Epoch [30/100], Loss:179.702225
Epoch [40/100], Loss:432.068848
Epoch [50/100], Loss:180.303070
Epoch [60/100], Loss:92.928787
Epoch [70/100], Loss:60.468525
Epoch [80/100], Loss:31.175318
Epoch [90/100], Loss:79.484528
Epoch [100/100], Loss:16.616610


In [32]:
preds = model(inputs)
preds

tensor([[ 59.0411,  72.1650],
        [ 82.0796,  98.6720],
        [115.5046, 135.6064],
        [ 31.8876,  46.3874],
        [ 95.4923, 110.1594],
        [ 58.0728,  71.2263],
        [ 81.7962,  98.2883],
        [115.8002, 135.9994],
        [ 32.8558,  47.3261],
        [ 96.1771, 110.7143],
        [ 58.7577,  71.7812],
        [ 81.1113,  97.7333],
        [115.7880, 135.9902],
        [ 31.2027,  45.8324],
        [ 96.4606, 111.0981]], grad_fn=<AddmmBackward0>)

In [33]:
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 57.,  69.],
        [ 80., 102.],
        [118., 134.],
        [ 21.,  38.],
        [104., 118.],
        [ 57.,  69.],
        [ 82., 100.],
        [118., 134.],
        [ 20.,  38.],
        [102., 120.]])

In [38]:
model(torch.tensor([[75,63,44.]]))

tensor([[56.0475, 69.0461]], grad_fn=<AddmmBackward0>)