<a href="https://colab.research.google.com/github/vash050/pytorch_start/blob/main/step_5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install opendatasets

In [8]:
import  opendatasets as od

загрузить другой dataset

In [79]:
od.download("https://www.kaggle.com/datasets/priyamchoksi/adult-census-income-dataset")

Please provide your Kaggle credentials to download this dataset. Learn more: http://bit.ly/kaggle-creds
Your Kaggle username: vash050
Your Kaggle Key: ··········
Dataset URL: https://www.kaggle.com/datasets/priyamchoksi/adult-census-income-dataset


100%|██████████| 450k/450k [00:00<00:00, 56.0MB/s]

In [80]:
import pandas as pd
data = pd.read_csv("/content/adult-census-income-dataset/adult.csv")

In [81]:
data.head

age workclass  fnlwgt     education  education.num marital.status  \
0   90         ?   77053       HS-grad              9        Widowed   
1   82   Private  132870       HS-grad              9        Widowed   
2   66         ?  186061  Some-college             10        Widowed   
3   54   Private  140359       7th-8th              4       Divorced   
4   41   Private  264663  Some-college             10      Separated   

          occupation   relationship   race     sex  capital.gain  \
0                  ?  Not-in-family  White  Female             0   
1    Exec-managerial  Not-in-family  White  Female             0   
2                  ?      Unmarried  Black  Female             0   
3  Machine-op-inspct      Unmarried  White  Female             0   
4     Prof-specialty      Own-child  White  Female             0   

   capital.loss  hours.per.week native.country income  
0          4356              40  United-States  <=50K  
1          4356              18  United-States  <=50K  
2          4356              40  United-States  <=50K  
3          3900              40  United-States  <=50K  
4          3900              40  United-States  <=50K

In [27]:
data_inputs = data.iloc[:, [0,1,2,3,4,5,6,7,8]]

In [36]:
import numpy as np

data_np_array = data_inputs.to_numpy('float32')

In [37]:
data_targets = data.iloc[:, [9]]

In [38]:
targets_np_array = data_targets.to_numpy(dtype='float32')

In [39]:
data_np_array

array([[  0.,   7.,   7., ...,  36.,   3.,   1.],
       [190.,   1.,   3., ...,  20.,   4.,   1.],
       [ 31.,   7.,   2., ...,  24.,   6.,   1.],
       ...,
       [  0.,   3.,   6., ...,  43.,   6.,  24.],
       [  0.,   6.,   6., ...,  46.,   7.,  24.],
       [ 18.,   7.,   4., ...,  61.,   7.,  24.]], dtype=float32)

In [40]:
targets_np_array.dtype

dtype('float32')

In [48]:
import torch

In [43]:
inputs = torch.from_numpy(data_np_array)
targets = torch.from_numpy(targets_np_array)

In [44]:
inputs

tensor([[  0.,   7.,   7.,  ...,  36.,   3.,   1.],
        [190.,   1.,   3.,  ...,  20.,   4.,   1.],
        [ 31.,   7.,   2.,  ...,  24.,   6.,   1.],
        ...,
        [  0.,   3.,   6.,  ...,  43.,   6.,  24.],
        [  0.,   6.,   6.,  ...,  46.,   7.,  24.],
        [ 18.,   7.,   4.,  ...,  61.,   7.,  24.]])

In [45]:
inputs.shape

torch.Size([944, 9])

In [60]:
w = torch.randn(1, 9, requires_grad=True)
b = torch.randn(1, requires_grad=True)
print(w)
print(b)

tensor([[-0.2974,  1.1254,  0.1041, -1.7531,  0.7283, -1.6074,  0.3551,  1.1351,
          1.6128]], requires_grad=True)
tensor([-0.3426], requires_grad=True)


In [56]:
def model(x):
  return x @ w.t() + b

In [61]:
preds = model(inputs)
print(preds)

tensor([[ 1.9037e+01],
        [-4.5383e+01],
        [ 1.4725e+01],
        [-6.8267e+00],
        [-1.5732e+02],
        [-2.0010e+01],
        [ 2.5957e+00],
        [-4.1075e+00],
        [-4.1578e+01],
        [-8.1407e+02],
        [-4.6979e+02],
        [-7.7781e+01],
        [-5.0794e+01],
        [-2.2306e+00],
        [-2.6969e+02],
        [ 2.6562e+01],
        [-1.0078e+01],
        [ 1.8558e+01],
        [ 1.5434e+01],
        [ 1.7039e+01],
        [ 1.7557e+01],
        [-4.7632e+01],
        [ 4.5502e+00],
        [ 2.4521e+01],
        [ 1.3375e+01],
        [ 1.5050e+01],
        [-9.0811e+01],
        [ 1.7948e+01],
        [ 1.8876e+01],
        [-1.2322e+02],
        [-9.4525e+01],
        [ 5.6655e+00],
        [ 1.3960e+01],
        [ 1.8682e+01],
        [-1.7221e+02],
        [ 3.3688e+01],
        [ 3.9956e+01],
        [ 1.7128e+01],
        [ 7.6117e-01],
        [ 2.8689e+01],
        [-2.6510e+01],
        [-1.7637e+02],
        [-1.5886e+01],
        [-2

In [62]:
print(targets)

tensor([[1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.],
        [0.],
      

In [64]:
diff = preds - targets
torch.sum(diff * diff) /diff.numel()

tensor(105759.5156, grad_fn=<DivBackward0>)

In [65]:
def mse(t1, t2):
  diff = t1 -t2
  return torch.sum(diff * diff) / diff.numel()

In [66]:
loss = mse(preds, targets)
print(loss)

tensor(105759.5156, grad_fn=<DivBackward0>)


In [67]:
loss.backward()

In [68]:
print(w)
print(w.grad)

tensor([[-0.2974,  1.1254,  0.1041, -1.7531,  0.7283, -1.6074,  0.3551,  1.1351,
          1.6128]], requires_grad=True)
tensor([[-7.2396e+05, -3.4322e+02, -3.3080e+02, -2.9126e+02, -4.9638e+02,
         -1.2752e+02, -3.5555e+03, -3.9061e+02, -1.2808e+03]])


In [69]:
print(b)
print(b.grad)

tensor([-0.3426], requires_grad=True)
tensor([-89.6033])


In [71]:
with torch.no_grad():
  w -= w.grad * 1e-5
  b -= b.grad * 1e-5

In [73]:
w, b

(tensor([[ 6.9422,  1.1289,  0.1074, -1.7502,  0.7333, -1.6062,  0.3906,  1.1390,
           1.6256]], requires_grad=True),
 tensor([-0.3417], requires_grad=True))

In [74]:
loss = mse(model(inputs), targets)
print(loss)

tensor(61156016., grad_fn=<DivBackward0>)


In [78]:

w.grad.zero_()
b.grad.zero_()
print(w.grad)
print(b.grad)

tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0.]])
tensor([0.])


In [ ]:
for i in range(100):
  preds = model(inputs)
  loss = mse(preds, targets)
  loss.backward()
  with torch.no_grad():
    w -= w.grad * 1e-5
    b -= b.grad * 1e-5
    w.grad.zero_()
    b.grad.zero_()